services:
  - type: web
    name: baty-car-app
    env: node
    rootDir: .
    buildCommand: npm run build
    startCommand: npm run server
    autoDeploy: true
    envVars:
      - key: PORT
        value: 5000
      - key: OPENALPR_API_KEY
        value: sk_DEMO
      - key: ALPR_REGION
        value: br
      - key: FASTAPI_BASE
        value: https://openalpr-fastapi-1.onrender.com

  - type: web
    name: openalpr-fastapi-1
    env: python
    rootDir: openalpr-fastapi
    buildCommand: pip install -r requirements.txt
    startCommand: bash start.sh
    autoDeploy: true
    envVars:
      - key: PORT
        value: 8000
